const ADMIN_ID="admin";const ADMIN_CODE="FrenchAuto2026";
const defaultReviews=[{id:101,name:"Mathéo L.",vehicle:"Audi RS6",rating:5,message:"Concession très professionnelle, accueil propre et véhicule livré rapidement.",date:"Aujourd'hui"},{id:102,name:"Sofia R.",vehicle:"BMW M4",rating:5,message:"Très bon service, vendeur sérieux et catalogue clair.",date:"Hier"}];
const defaultVehicles=[{id:1,brand:"Audi",name:"RS6 Avant",type:"auto",price:"109 900 €",image:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=90",description:"Break sportif premium, finition haut de gamme et performances exceptionnelles.",isNew:true},{id:2,brand:"BMW",name:"M4 Competition",type:"auto",price:"89 900 €",image:"https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=900&q=90",description:"Coupé sportif élégant, puissant et idéal pour les passionnés de conduite.",isNew:true},{id:3,brand:"Yamaha",name:"MT-09",type:"moto",price:"10 499 €",image:"https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=90",description:"Roadster nerveux, look agressif et sensations garanties.",isNew:true}];
let vehicles=JSON.parse(localStorage.getItem("frenchAutoVehicles"))||defaultVehicles;let reviews=JSON.parse(localStorage.getItem("frenchAutoReviews"))||defaultReviews;let marquee=localStorage.getItem("frenchAutoMarquee")||"NOUVEAUTÉ : Découvrez nos nouveaux arrivages premium chez French Auto.";let contactPhone=localStorage.getItem("frenchAutoPhone")||"À compléter";let contactDiscord=localStorage.getItem("frenchAutoDiscord")||".gg/perpinyarp";let contactAddress=localStorage.getItem("frenchAutoAddress")||"Adresse de la concession<br>À compléter";let gpsImage=localStorage.getItem("frenchAutoGpsImage")||"https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=900&q=80";let currentTypeFilter="all";const $=id=>document.getElementById(id);
function initSite(){$("marqueeText").innerHTML=marquee.replace("NOUVEAUTÉ","<b>NOUVEAUTÉ</b>");$("newMarqueeText").value=marquee;$("contactPhone").textContent=contactPhone;$("contactDiscord").textContent=contactDiscord;$("contactAddress").innerHTML=contactAddress;$("gpsImage").src=gpsImage;$("adminPhoneInput").value=contactPhone!=="À compléter"?contactPhone:"";$("adminDiscordInput").value=contactDiscord;$("adminAddressInput").value=contactAddress.replace(/<br>/g,"
");$("gpsImageInput").value=gpsImage;renderBrandFilter();renderCatalogue("all");renderNewArrivals();renderHomeReview();updateStats();}
function saveData(){localStorage.setItem("frenchAutoVehicles",JSON.stringify(vehicles));updateStats()}function saveReviewsData(){localStorage.setItem("frenchAutoReviews",JSON.stringify(reviews))}
function updateStats(){let t=vehicles.length,c=vehicles.filter(v=>v.type==="auto").length,m=vehicles.filter(v=>v.type==="moto").length;if($("statTotal")){$("statTotal").textContent=t;$("statCars").textContent=c;$("statMotos").textContent=m}}
function showPage(pageId,btn=null){document.querySelectorAll("section").forEach(s=>s.classList.remove("active"));$(pageId).classList.add("active");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active"));if(btn)btn.classList.add("active");else{let i={home:0,catalogue:1,contact:2,admin:3}[pageId];if(i!==undefined)document.querySelectorAll(".nav-btn")[i].classList.add("active")}if(pageId==="catalogue")renderCatalogue("all");if(pageId==="home")renderHomeReview();if(pageId==="admin"){renderAdminList();renderAdminReviews()}window.scrollTo({top:0,behavior:"smooth"})}
function openCatalogue(type){showPage("catalogue");renderCatalogue(type)}
function vehicleCard(v){return `<div class="vehicle-card"><img src="${v.image}" alt="${v.name}" onerror="this.src='https://via.placeholder.com/900x500/111111/ffffff?text=French+Auto'"><div class="vehicle-info"><span class="badge">${v.type==='auto'?'Auto':'Moto'}</span><span class="badge">${v.brand||'Sans marque'}</span>${v.isNew?'<span class="badge new-badge">Nouveau</span>':''}<h3>${v.brand?v.brand+' ':''}${v.name}</h3><p>${v.description}</p><div class="price">${v.price}</div></div></div>`}
function renderBrandFilter(){let select=$("brandFilter");if(!select)return;let selected=select.value||"all";let brands=[...new Set(vehicles.map(v=>v.brand).filter(Boolean))].sort();select.innerHTML='<option value="all">Toutes les marques</option>'+brands.map(b=>`<option value="${b}">${b}</option>`).join("");select.value=brands.includes(selected)?selected:"all"}
function renderCatalogue(filter="all",activeBtn=null){currentTypeFilter=filter;let grid=$("catalogueGrid");if(!grid)return;renderBrandFilter();document.querySelectorAll(".filter-btn").forEach(b=>b.classList.remove("active"));if(activeBtn)activeBtn.classList.add("active");let brand=$("brandFilter")?$("brandFilter").value:"all";let data=filter==="all"?vehicles:vehicles.filter(v=>v.type===filter);if(brand!=="all")data=data.filter(v=>v.brand===brand);grid.innerHTML=data.length?data.map(vehicleCard).join(""):"<p>Aucun véhicule disponible.</p>"}
function renderNewArrivals(){let grid=$("newArrivalsGrid");if(!grid)return;let data=vehicles.filter(v=>v.isNew).slice(-6).reverse();grid.innerHTML=data.length?data.map(vehicleCard).join(""):"<p>Aucun nouveau véhicule pour le moment.</p>"}
function stars(r){return "★".repeat(Number(r))+"☆".repeat(5-Number(r))}function renderGlobalRating(){let avg=reviews.length?(reviews.reduce((a,b)=>a+Number(b.rating),0)/reviews.length).toFixed(1):0;let html=`<div><strong>${avg}/5</strong><div class="review-stars">${stars(Math.round(avg))}</div><small>${reviews.length} avis clients</small></div><div><small>Note générale des clients French Auto</small></div>`;if($("globalRatingHome"))$("globalRatingHome").innerHTML=html;if($("globalRatingModal"))$("globalRatingModal").innerHTML=html}
function renderHomeReview(){let box=$("lastReviewHome");if(!box)return;renderGlobalRating();let r=reviews[reviews.length-1];box.innerHTML=r?`<strong>${r.name}</strong><div class="review-stars">${stars(r.rating)}</div><p><strong>Véhicule :</strong> ${r.vehicle}<br><br>“${r.message}”</p><small>${r.date}</small>`:"<p>Aucun avis pour le moment.</p>";renderAllReviews()}
function renderAllReviews(){let grid=$("allReviewsGrid");if(!grid)return;grid.innerHTML=reviews.length?reviews.slice().reverse().map(r=>`<div class="review-full-card"><strong>${r.name}</strong><div class="review-stars">${stars(r.rating)}</div><p><strong>Véhicule :</strong> ${r.vehicle}<br><br>${r.message}</p><small style="color:#777">${r.date}</small></div>`).join(""):"<p>Aucun avis disponible.</p>"}
function openAllReviewsModal(){$("allReviewsModal").classList.add("open")}function closeAllReviewsModal(){$("allReviewsModal").classList.remove("open")}function openReviewModal(){$("reviewModal").classList.add("open")}function closeReviewModal(){$("reviewModal").classList.remove("open")}
function saveReview(){let name=$("reviewName").value.trim(),vehicle=$("reviewVehicle").value.trim(),rating=$("reviewRating").value,msg=$("reviewMessage").value.trim();if(!name||!vehicle||!msg)return alert("Merci de remplir tous les champs.");reviews.push({id:Date.now(),name,vehicle,rating,message:msg,date:new Date().toLocaleDateString('fr-FR')});saveReviewsData();$("reviewName").value="";$("reviewVehicle").value="";$("reviewRating").value="5";$("reviewMessage").value="";renderHomeReview();renderAdminReviews();closeReviewModal();alert("Avis publié.")}
function renderAdminReviews(){let list=$("adminReviewList");if(!list)return;list.innerHTML=reviews.length?reviews.slice().reverse().map(r=>`<div class="admin-item"><div style="font-size:24px;color:var(--gold)">${stars(r.rating)}</div><div><strong>${r.name}</strong><br><small>${r.message}</small></div><div><button class="admin-btn danger small-btn" onclick="deleteReview('${r.id}')">Supprimer</button></div></div>`).join(""):"<p>Aucun avis.</p>"}
function deleteReview(id){reviews=reviews.filter(r=>String(r.id)!==String(id));saveReviewsData();renderHomeReview();renderAdminReviews()}function clearAllReviews(){reviews=[];saveReviewsData();renderHomeReview();renderAdminReviews()}
function loginAdmin(){let id=$("adminIdInput").value,code=$("adminCodeInput").value;if(id===ADMIN_ID&&code===ADMIN_CODE){$("loginBox").classList.add("hidden");$("adminContent").classList.remove("hidden");renderAdminList();renderAdminReviews()}else $("loginError").textContent="Identifiant ou code incorrect."}
function saveMarquee(){let text=$("newMarqueeText").value.trim();if(!text)return alert("Entre un texte.");localStorage.setItem("frenchAutoMarquee",text);$("marqueeText").innerHTML=text.replace("NOUVEAUTÉ","<b>NOUVEAUTÉ</b>");alert("Texte mis à jour.")}function savePhone(){let phone=$("adminPhoneInput").value.trim();if(!phone)return alert("Entre un numéro.");localStorage.setItem("frenchAutoPhone",phone);$("contactPhone").textContent=phone;alert("Téléphone mis à jour.")}function saveDiscord(){let discord=$("adminDiscordInput").value.trim();if(!discord)return alert("Entre un lien Discord.");localStorage.setItem("frenchAutoDiscord",discord);$("contactDiscord").textContent=discord;alert("Discord mis à jour.")}function saveAddress(){let address=$("adminAddressInput").value.trim();if(!address)return alert("Entre une adresse.");address=address.replace(/
/g,"<br>");localStorage.setItem("frenchAutoAddress",address);$("contactAddress").innerHTML=address;alert("Adresse mise à jour.")}
function previewGpsImage(e){let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=x=>{$("gpsImageInput").value=x.target.result;$("gpsPreview").src=x.target.result;$("gpsPreviewBox").style.display="block"};reader.readAsDataURL(file)}function saveGpsImage(){let img=$("gpsImageInput").value.trim();if(!img)return alert("Entre une image.");localStorage.setItem("frenchAutoGpsImage",img);$("gpsImage").src=img;$("gpsPreview").src=img;$("gpsPreviewBox").style.display="block";alert("Image GPS mise à jour.")}
function previewVehicleImage(e){let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=x=>{$("vehicleImage").value=x.target.result;$("imagePreview").src=x.target.result;$("imagePreviewBox").style.display="block"};reader.readAsDataURL(file)}
function saveVehicle(){let id=$("editId").value,brand=$("vehicleBrand").value.trim(),name=$("vehicleName").value.trim(),type=$("vehicleType").value,price=$("vehiclePrice").value.trim(),image=$("vehicleImage").value.trim(),description=$("vehicleDescription").value.trim(),isNew=$("vehicleNew").checked;if(!brand||!name||!price||!image||!description)return alert("Merci de remplir tous les champs.");if(id)vehicles=vehicles.map(v=>String(v.id)===String(id)?{id:Number(id),brand,name,type,price,image,description,isNew}:v);else vehicles.push({id:Date.now(),brand,name,type,price,image,description,isNew});saveData();resetForm();renderBrandFilter();renderCatalogue("all");renderNewArrivals();renderAdminList();alert("Véhicule enregistré.")}
function renderAdminList(){let list=$("adminVehicleList");if(!list)return;list.innerHTML=vehicles.length?vehicles.map(v=>`<div class="admin-item"><img src="${v.image}" onerror="this.src='https://via.placeholder.com/160x100/111111/ffffff?text=Auto'"><div><strong>${v.brand?v.brand+' ':''}${v.name}</strong><br><small>${v.type.toUpperCase()} — ${v.price} ${v.isNew?'— NOUVEAUTÉ':''}</small></div><div><button class="admin-btn small-btn" onclick="editVehicle('${v.id}')">Modifier</button><button class="admin-btn danger small-btn" onclick="deleteVehicle('${v.id}')">Supprimer</button></div></div>`).join(""):"<p>Aucun véhicule.</p>"}
function editVehicle(id){let v=vehicles.find(x=>String(x.id)===String(id));if(!v)return;$("formTitle").textContent="Modifier le véhicule";$("editId").value=v.id;$("vehicleName").value=v.name;$("vehicleBrand").value=v.brand||"";$("vehicleType").value=v.type;$("vehiclePrice").value=v.price;$("vehicleImage").value=v.image;$("vehicleDescription").value=v.description;$("vehicleNew").checked=!!v.isNew;$("imagePreview").src=v.image;$("imagePreviewBox").style.display="block"}function deleteVehicle(id){vehicles=vehicles.filter(v=>String(v.id)!==String(id));saveData();renderCatalogue("all");renderNewArrivals();renderAdminList()}function clearAllVehicles(){vehicles=[];saveData();renderCatalogue("all");renderNewArrivals();renderAdminList()}function resetDefaultVehicles(){vehicles=[...defaultVehicles];saveData();renderCatalogue("all");renderNewArrivals();renderAdminList()}function resetForm(){$("formTitle").textContent="Ajouter un véhicule";$("editId").value="";$("vehicleName").value="";$("vehicleBrand").value="";$("vehicleType").value="auto";$("vehiclePrice").value="";$("vehicleImage").value="";$("vehicleImageFile").value="";$("vehicleDescription").value="";$("vehicleNew").checked=false;$("imagePreviewBox").style.display="none";$("imagePreview").src=""}initSite();